### PR TITLE
NUS COM3 Building World

### PR DESCRIPTION
**Pull request by NamTruongTran**
How to start the COM3 Building World:

roslaunch arena_bringup start_arena.launch simulator:=gazebo map_file:=arena_nus_campus_faculty_of_arts_and_social_science_com3_building local_planner:=teb model:=jackal

### CODE REVIEW

**Comment by NamTruongTran** [comment]
@voshch 
@linhdoan8 
Kindly check. Thank you.

**Comment by linhdoan8** [comment]
Pls change the file name to nus-large, nus-small. The file name is way too long

**Review by voshch — CHANGES_REQUESTED** [review]
> Pls change the file name to nus-large, nus-small. The file name is way too long

+1

**Comment by voshch** [comment]
Looks great otherwise, can be merged after rename.
Also add 2-3 scenarios for this map in https://github.com/Arena-Rosnav/arena-rosnav.

**Comment by NamTruongTran** [comment]
@voshch
@linhdoan8

I added the COM2 Building World. Next, i will add the COM1 Building world and the complete area.
You can see pictures of the world in _arena-simulation-setup/worlds/arena_nus_com3_building/photos_

**How to start the COM3 Building World:**

roslaunch arena_bringup start_arena.launch simulator:=gazebo map_file:=arena_nus_com3_building local_planner:=teb model:=jackal

**How to start the COM2 Building World:**

roslaunch arena_bringup start_arena.launch simulator:=gazebo map_file:=arena_nus_com2_building local_planner:=teb model:=jackal

**Comment by voshch** [comment]
image
the scale can't be right, jackal is only 25cm tall

**Comment by NamTruongTran** [comment]
@voshch

Changes:
- Rescaled
- Minor changes to the models
- Add NUS COM1 World

Pictures in: arena-simulation-setup/worlds/arena_nus_com1_building/photos
Pictures in: arena-simulation-setup/worlds/arena_nus_com2_building/photos
Pictures in: arena-simulation-setup/worlds/arena_nus_com3_building/photos

**How to start the COM1 Building World:**

roslaunch arena_bringup start_arena.launch simulator:=gazebo map_file:=arena_nus_com1_building local_planner:=teb model:=jackal

**How to start the COM2 Building World:**

roslaunch arena_bringup start_arena.launch simulator:=gazebo map_file:=arena_nus_com2_building local_planner:=teb model:=jackal

**How to start the COM3 Building World:**

roslaunch arena_bringup start_arena.launch simulator:=gazebo map_file:=arena_nus_com3_building local_planner:=teb model:=jackal

**Comment by NamTruongTran** [comment]
@voshch

Created the world arena_corridor.

**Review by linhdoan8 — APPROVED** [review]

**Pull request merged**
